# Generated by Django 6.0 on 2025-12-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstatisticaEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("estado", models.CharField(max_length=2)),
                ("area", models.CharField(max_length=20)),
                ("media_nota", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="nota_ciencias",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="nota_humanas",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="nota_linguagens",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="nota_matematica",
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota_enem_ciencias",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota_enem_humanas",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota_enem_linguagens",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="nota_enem_matematica",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.CreateModel(
            name="Simulado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("tipo", models.CharField(max_length=50)),
                (
                    "nota_linguagens",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "nota_matematica",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("nota_ciencias", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nota_humanas", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="enem.aluno"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Estatistica",
        ),
    ]
